VascoSch92/symmetria

.github/workflows/check-pr-title.yml
.github/workflows/code-style.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.readthedocs.yaml
CHANGELOG.md
CONTRIBUTING.md
Makefile

The PR takes care of issue #11 
Checklist:
Note that the last two points will be made in a separate PR

[MAINTENANCE] Add ci/cd

---

CHANGELOG.md
tests/tests_cycle/test_cases.py
tests/tests_cycle/test_constructors.py
tests/tests_cycle_decomposition/test_cases.py
tests/tests_cycle_decomposition/test_constructors.py
tests/tests_cycle_decomposition/test_magic_methods.py
tests/tests_factory.py

[MAINTENANCE] improve API tests

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation_issue.md
.github/ISSUE_TEMPLATE/enhancement_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/maintenance_issue.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/report_all_other_issues_or_questions.md
CHANGELOG.md

[MAINTENANCE] add template for issue

---

symmetria/elements/permutation.py

[DOC] improve docstring for `one_line_notation`

---

CHANGELOG.md
docs/source/pages/API_reference/elements/index.rst
symmetria/elements/_interface.py
symmetria/elements/cycle.py
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
tests/test_factory.py
tests/tests_cycle/test_cases.py
tests/tests_cycle/test_generic_method.py
tests/tests_cycle_decomposition/test_cases.py
tests/tests_cycle_decomposition/test_generic_methods.py
tests/tests_permutation/test_cases.py
tests/tests_permutation/test_generic_methods.py

[FEATURE] Add inverse

---

CHANGELOG.md
docs/source/pages/API_reference/elements/index.rst
symmetria/elements/_interface.py
symmetria/elements/cycle.py
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
tests/test_factory.py
tests/tests_cycle/test_cases.py
tests/tests_cycle/test_generic_method.py
tests/tests_cycle_decomposition/test_cases.py
tests/tests_cycle_decomposition/test_generic_methods.py
tests/tests_permutation/test_cases.py
tests/tests_permutation/test_generic_methods.py

[FEATURE] Add `is_even` and `is_odd` methods

---

CHANGELOG.md
docs/source/pages/API_reference/elements/index.rst
symmetria/elements/_interface.py
symmetria/elements/cycle.py
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
tests/test_factory.py
tests/tests_cycle/test_generic_method.py
tests/tests_cycle_decomposition/test_cases.py
tests/tests_cycle_decomposition/test_generic_methods.py
tests/tests_permutation/test_cases.py
tests/tests_permutation/test_generic_methods.py

[FEATURE] Add cycle type

---

.github/workflows/tests.yml
CHANGELOG.md
Makefile
symmetria/elements/cycle.py
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py

[MAINTENANCE] Add doctest

---

.github/ISSUE_TEMPLATE/all_other_issues.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation_issue.md
.github/ISSUE_TEMPLATE/documentation_issue.yml
.github/ISSUE_TEMPLATE/enhancement_report.md
.github/ISSUE_TEMPLATE/enhancement_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/maintenance_issue.md
.github/ISSUE_TEMPLATE/maintenance_issue.yml
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/question.yml
.github/ISSUE_TEMPLATE/report_all_other_issues_or_questions.md

[MAINTENANCE] Fix issue templates

---

README.md

Small PR to update the logo in the README.md as it was not properly rendered
**Checklist:**

[MAINTENANCE] Update logo in README.md

---

symmetria/elements/_interface.py
symmetria/elements/cycle.py
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
tests/tests_meta/test_order.py

[MAINTENANCE] Re-work meta tests

---

CONTRIBUTING.md
README.md
pyproject.toml

[DOC] Update links for documentations and refactoring READ.me

---

CHANGELOG.md
pyproject.toml
symmetria/__init__.py

[RELEASE] 0.0.2

---

README.md

[MAINTENANCE] Update README.md

---

CHANGELOG.md
pyproject.toml
symmetria/__init__.py

[RELEASE] 0.0.3

---

CHANGELOG.md
docs/source/pages/API_reference/elements/index.rst
symmetria/elements/_interface.py
symmetria/elements/cycle.py
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
tests/test_factory.py
tests/tests_cycle/test_cases.py
tests/tests_cycle/test_generic_method.py
tests/tests_cycle_decomposition/test_cases.py
tests/tests_cycle_decomposition/test_generic_methods.py
tests/tests_permutation/test_cases.py
tests/tests_permutation/test_generic_methods.py

[FEATURE] Add method `is_regular`

---

CHANGELOG.md
docs/source/pages/API_reference/elements/index.rst
symmetria/elements/_interface.py
symmetria/elements/cycle.py
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
tests/test_factory.py
tests/tests_cycle/test_cases.py
tests/tests_cycle/test_generic_method.py
tests/tests_cycle_decomposition/test_cases.py
tests/tests_cycle_decomposition/test_generic_methods.py
tests/tests_permutation/test_cases.py
tests/tests_permutation/test_generic_methods.py

[FEATURE] Add method `inversions` and `image`

---

symmetria/elements/permutation.py

There is no entry in the `CHANGELOG.md`, because this is more or less a fix as I forgot to put `_image` in the `__slots__ `when the property `image` was introduced.
**Checklist:**

[ENHANCEMENT] Update `__slots__` of class `Permutation`

---

CHANGELOG.md

Fix a missing entry in the `CHANGELOG.md` of the previous PR.
**Checklist:**

[MAINTENANCE] Entry in CHANGELOG.md

---

CHANGELOG.md
pyproject.toml
symmetria/__init__.py

[RELEASE] 0.0.4

---

symmetria/elements/_interface.py
symmetria/elements/cycle.py
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
tests/tests_cycle/test_cases.py

[DOC] Add missing example in docstrings

---

CHANGELOG.md
docs/source/pages/API_reference/elements/index.rst
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
tests/test_factory.py
tests/tests_cycle_decomposition/test_cases.py
tests/tests_cycle_decomposition/test_generic_methods.py
tests/tests_permutation/test_cases.py
tests/tests_permutation/test_generic_methods.py

[FEATURE] Add method `descents`

---

CHANGELOG.md
docs/source/pages/API_reference/elements/index.rst
symmetria/elements/_interface.py
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
tests/test_factory.py
tests/tests_cycle_decomposition/test_cases.py
tests/tests_cycle_decomposition/test_generic_methods.py
tests/tests_permutation/test_cases.py
tests/tests_permutation/test_constructors.py
tests/tests_permutation/test_generic_methods.py

[FEATURE] Implement `exceedences` method

---

CHANGELOG.md
docs/source/pages/API_reference/elements/index.rst
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
tests/tests_cycle_decomposition/test_cases.py
tests/tests_cycle_decomposition/test_generic_methods.py
tests/tests_permutation/test_cases.py
tests/tests_permutation/test_generic_methods.py

[FEATURE] Add method `records`

---

CHANGELOG.md
pyproject.toml
symmetria/__init__.py

[RELEASE] 0.0.5

---

.pre-commit-config.yaml
docs/source/pages/API_reference/generators/generate.rst
docs/source/pages/API_reference/generators/index.rst
symmetria/__init__.py
symmetria/generators/_algorithms.py
symmetria/generators/api.py
tests/tests_generators/test_api.py
tests/tests_generators/test_cases.py

[FEATURE] Add `lexicographic` algorithm

---

.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md

[MAINTENANCE] Fix templates for PR and Issues

---

CHANGELOG.md
README.md
docs/source/pages/API_reference/elements/index.rst
docs/source/pages/API_reference/generators/generate.rst
docs/source/pages/getting_started/quickstart.rst
pyproject.toml
symmetria/elements/_base.py
symmetria/elements/cycle.py
symmetria/elements/cycle_decomposition.py
symmetria/generators/_algorithms.py
symmetria/generators/api.py
tests/tests_elements/tests_cycle/test_cases.py
tests/tests_elements/tests_cycle/test_generic_method.py
tests/tests_elements/tests_cycle/test_magic_methods.py
tests/tests_elements/tests_cycle_decomposition/test_magic_methods.py

[MAINTENANCE][DOC] Fixes and documentation

---

CHANGELOG.md
pyproject.toml
symmetria/__init__.py

[RELEASE] 0.1.0

---

CHANGELOG.md
pyproject.toml
symmetria/__init__.py

[RELEASE] 0.1.1

---

CHANGELOG.md
pyproject.toml
symmetria/__init__.py

[RELEASE] 0.2.0

---

CHANGELOG.md
pyproject.toml
symmetria/__init__.py

[RELEASE] 0.3.1

---

CHANGELOG.md
symmetria/__init__.py
symmetria/generators/algorithm/api.py
tests/tests_generators/test_api.py

[MAINTENANCE] Deprecated old generator method

---

CHANGELOG.md
pyproject.toml
symmetria/__init__.py

[RELEASE] 0.3.2

---

.pre-commit-config.yaml
CHANGELOG.md
Makefile
pyproject.toml
symmetria/cli/_commands.py
symmetria/elements/_utils.py
symmetria/elements/_validators.py
symmetria/elements/cycle.py
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
symmetria/generators/algorithm/api.py
symmetria/generators/random/api.py
tests/tests_meta/test_order.py

[MAINTENANCE] Add static analysis check (`mypy`)

---

CHANGELOG.md
pyproject.toml
symmetria/__init__.py

[RELEASE] 0.3.3

---

CHANGELOG.md
pyproject.toml
symmetria/__init__.py

[RELEASE] 0.3.4

---

CHANGELOG.md
symmetria/elements/_types.py
symmetria/elements/cycle.py
symmetria/elements/cycle_decomposition.py
symmetria/elements/permutation.py
tests/tests_elements/tests_cycle/test_cases.py
tests/tests_elements/tests_cycle_decomposition/test_cases.py
tests/tests_elements/tests_permutation/test_cases.py

[ENHANCEMENT] Delete use of type hint `Any`
